
arch:
  - amd64
  - ppc64le
language: java
jdk:
- openjdk11
- openjdk12
- openjdk13
- openjdk14
- openjdk15


before_install: 
    - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then mkdir -p /opt/maven; sudo apt-get update; sudo apt-get install maven;export MAVEN_HOME=/opt/maven; export PATH=${MAVEN_HOME}/bin:${PATH};  fi
install:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
